APIMainBundle:
    resource: "@APIMainBundle/Resources/config/routing.yml"
    prefix:   /api
    
## Doc
#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /api/doc